all: 
	gcc -fopenmp omp_solved_bug2.c -o omp-solved2
	gcc -fopenmp omp_solved_bug3.c -o omp-solved3
	gcc -fopenmp omp_solved_bug4.c -o omp-solved4
	gcc -fopenmp omp_solved_bug5.c -o omp-solved5
	gcc -fopenmp omp_solved_bug6.c -o omp-solved6
	g++ -fopenmp omp-scan.cpp -o omp-scan
	g++ -Wall -std=c++11 -fopenmp gs2D-omp.cpp -o gs2D
